### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by WarriorFromLongAgo** [rookie-ricardo/BeanMappingKey#2]
**IntelliJ desc**
* IntelliJ platform : 
* Version : 

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: July 8, 2022
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2016M
Cores: 8
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: io.zhile.research.ide-eval-resetter (2.3.5), com.github.copilot (1.1.24.1610), com.github.wangji92.arthas.plugin (2.37), com.alibaba.p3c.smartfox (2.1.1), com.kyexpress.fmk.debug.ui (2.5.1), com.kyexpress.plugins.openapi-generator (1.1.0), org.rookie.plugins.BeanMappingKey (2.0), org.sonarlint.idea (6.7.0.45926), MavenRunHelper (4.13.203.000.0), org.jetbrains.plugins.vue (211.6693.111), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), JRebelPlugin (2022.2.1), cn.yiiguxing.plugin.translate (3.3.1-203u212.patch.1), com.baomidou.plugin.idea.mybatisx (1.5.4)
Kotlin: 211-1.5.0-release-759-IJ6693.72

**Describe the bug**

![IMG20220608095252](https://user-images.githubusercontent.com/56761731/172514355-56f654ab-4343-40d7-8444-93a21b568089.png)

我在下述代码块里面，右键 ctrl+m 是灰色的，无法点击（如图所示）
```java
public class Convert {
    public FileNameUrlV2 convert(FileNameUrl fileNameUrl){
        FileNameUrlV2 fileNameUrlV2 = new FileNameUrlV2();
        
        return fileNameUrlV2;
    }
}

```

```java
public class FileNameUrl {
    private String fileName;
    private String url;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
}
```

```java
public class FileNameUrlV2 {
    private String fileName;
    private String url;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
}

```

**Comment by rookie-ricardo** [comment]
我晚上看一下，请问您是否将鼠标选中某变量或者类之后再进行右键？

**Comment by rookie-ricardo** [comment]
我晚上看一下，请问您是否将鼠标选中某变量或者类之后再进行右键？

**Comment by rookie-ricardo** [comment]
@WarriorFromLongAgo 我晚上看一下，请问您是否将鼠标选中某变量或者类之后再进行右键？

**Comment by rookie-ricardo** [comment]
@WarriorFromLongAgo 我对您的示例尝试了好几次都可以生成，生成之前需要双击选中变量或者类才能进行代码生成。
直接在这个页面右键插件当然是无法知道你想生成哪个类。Good Luck

**Comment by WarriorFromLongAgo** [comment]
我试了一下。。。确实是这样。。。感觉可以录个简单的视频说明一下如何使用。

感觉奇怪的交互。

**Comment by WarriorFromLongAgo** [comment]
同时，只可以将一个类保存在剪切板里面，不可以同时将两个类保存在剪切板里面嘛

也就是如下所示
可以：a.setA()，或者，b.setA()
不可以：同时生成a.setA(b.getA)

如果支持同时生成，不知道是什么样子的。

**Comment by rookie-ricardo** [comment]
> 同时，只可以将一个类保存在剪切板里面，不可以同时将两个类保存在剪切板里面嘛
> 
> 也就是如下所示 可以：a.setA()，或者，b.setA() 不可以：同时生成a.setA(b.getA)
> 
> 如果支持同时生成，不知道是什么样子的。

是具有这个功能的，方法生成的时候会自动匹配，具体用法可以查看：https://juejin.cn/post/7083384279123623966。

关于上面您觉得交互奇怪，考虑到具体的使用场景一般都是具有很多代码，如果不人为选中，自动识别不可能准确，就像CTRL+F 也需要你输入你想搜索的东西一样。
