### ISSUE TITLE
为什么右键的BeanMappingKey是灰色的不能使用呢？

### ISSUE THREAD

**Issue by hmh38324** [rookie-ricardo/BeanMappingKey#3]
图片如下：
![image](https://user-images.githubusercontent.com/52850160/203454766-03b79b90-4ad8-404d-a614-3bcbf84e0e27.png)

**Comment by rookie-ricardo** [comment]
> 图片如下： ![image](https://user-images.githubusercontent.com/52850160/203454766-03b79b90-4ad8-404d-a614-3bcbf84e0e27.png)

你需要双击选择方法或者双击选中类名然后进行右键点击。
这是我在掘金写的推广文章：https://juejin.cn/post/7083384279123623966
你这个截图一看就是没有选中某个方法或者类名，而是直接在页面上进行右键。
