### ISSUE TITLE
可以支持2023版本吗？

### ISSUE THREAD

**Issue by icellus** [rookie-ricardo/BeanMappingKey#6]
**IntelliJ desc**
* IntelliJ platform : 
* Version : 2023.2
可以支持2023版本吗？

**Comment by rookie-ricardo** [comment]
> **IntelliJ desc**
> 
> * IntelliJ platform :
> * Version : 2023.2
>   可以支持2023版本吗？

我注意到了你这个问题，目前我的插件最新版本是 2.5 ，IDEA 的兼容性报告里面显示我这个插件是支持2023版本的，并且支持尚未发布的2023.3版本。
你能截图或者更加详细描述这个问题吗？

**Comment by icellus** [comment]
![image](https://github.com/rookie-ricardo/BeanMappingKey/assets/23291667/6f6a43bd-b77e-4962-a6ad-41a30149af86)
![image](https://github.com/rookie-ricardo/BeanMappingKey/assets/23291667/f0f50a26-5a6a-41ee-ae2a-6e9381402d6f)
![image](https://github.com/rookie-ricardo/BeanMappingKey/assets/23291667/5fd5235e-a30c-4426-9853-eadfb2586d9b)
https://plugins.jetbrains.com/plugin/18264-beanmappingkey

您好，这是我这边的详细截图
