### ISSUE TITLE
2023.2版本支持

### ISSUE THREAD

**Issue by icellus** [rookie-ricardo/BeanMappingKey#7]
![image](https://github.com/rookie-ricardo/BeanMappingKey/assets/23291667/6f6a43bd-b77e-4962-a6ad-41a30149af86)
![image](https://github.com/rookie-ricardo/BeanMappingKey/assets/23291667/f0f50a26-5a6a-41ee-ae2a-6e9381402d6f)
![image](https://github.com/rookie-ricardo/BeanMappingKey/assets/23291667/5fd5235e-a30c-4426-9853-eadfb2586d9b)
https://plugins.jetbrains.com/plugin/18264-beanmappingkey

您好，这是我这边的详细截图

_Originally posted by @icellus in https://github.com/rookie-ricardo/BeanMappingKey/issues/6#issuecomment-1833031934_

**Comment by rookie-ricardo** [comment]
> ![image](https://private-user-images.githubusercontent.com/23291667/286802811-6f6a43bd-b77e-4962-a6ad-41a30149af86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNDcsIm5iZiI6MTcwMjU2Njg0NywicGF0aCI6Ii8yMzI5MTY2Ny8yODY4MDI4MTEtNmY2YTQzYmQtYjc3ZS00OTYyLWE2YWQtNDFhMzAxNDlhZjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZWY0NTFjMzQyYTJjMGZmZmQzM2QyNWE1YWE3MjYxZTY4MjRhN2Y3NWRkYWEyMTU1MmJkMDVhMzVlNzYyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_fvc8GrDU9Herq7iEjd2UJTine0yt8I3qZ0hk7OZV8) ![image](https://private-user-images.githubusercontent.com/23291667/286802877-f0f50a26-5a6a-41ee-ae2a-6e9381402d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNDcsIm5iZiI6MTcwMjU2Njg0NywicGF0aCI6Ii8yMzI5MTY2Ny8yODY4MDI4NzctZjBmNTBhMjYtNWE2YS00MWVlLWFlMmEtNmU5MzgxNDAyZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZmQ3YzliZGU5MzQ3ZDQ1OWRiY2FiZDQ2YzM2ZjFjYWI3N2RmNTk0YjI3MTM2MTY0N2UzNjU1N2Q3MGEwZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnJaB3gNOBuDoJxQu0-EFXVt8XRLxeHQkseQAZX01LE) ![image](https://private-user-images.githubusercontent.com/23291667/286803027-5fd5235e-a30c-4426-9853-eadfb2586d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNDcsIm5iZiI6MTcwMjU2Njg0NywicGF0aCI6Ii8yMzI5MTY2Ny8yODY4MDMwMjctNWZkNTIzNWUtYTMwYy00NDI2LTk4NTMtZWFkZmIyNTg2ZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlN2E5NzM5YmU4ZWIzMTNkOTdlOTkxZDAzMDk5NmE3MzYzODEzODUzNjA0MzExM2Y3YjNhZmE4NDZhOGVkZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W-xPAMkdu0mxhGJiamMUpvBAyghZcNPM6803r_xoau8) https://plugins.jetbrains.com/plugin/18264-beanmappingkey
> 
> 您好，这是我这边的详细截图
> 
> _Originally posted by @icellus in [#6 (comment)](https://github.com/rookie-ricardo/BeanMappingKey/issues/6#issuecomment-1833031934)_

你已经安装的话，就是代表已经支持你这个版本了，但是我看你的截图似乎你是想说明 这个插件没办法用？如果是这样的话，我建议你
1. 重新打开IDE，等待索引走完之后再使用，这个插件和所有插件一样依赖的是IDE内部的上下文对象，有时候它会失效。
2. 双击类名，右键看一下。

版本是兼容到了2023.3的，可以给你看一下截图：
<img width="806" alt="image" src="https://github.com/rookie-ricardo/BeanMappingKey/assets/33930171/1c3cfa79-8fe0-495d-aa5f-5355ae1a71f1">

**Comment by icellus** [comment]
> > ![image](https://private-user-images.githubusercontent.com/23291667/286802811-6f6a43bd-b77e-4962-a6ad-41a30149af86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNDcsIm5iZiI6MTcwMjU2Njg0NywicGF0aCI6Ii8yMzI5MTY2Ny8yODY4MDI4MTEtNmY2YTQzYmQtYjc3ZS00OTYyLWE2YWQtNDFhMzAxNDlhZjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZWY0NTFjMzQyYTJjMGZmZmQzM2QyNWE1YWE3MjYxZTY4MjRhN2Y3NWRkYWEyMTU1MmJkMDVhMzVlNzYyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_fvc8GrDU9Herq7iEjd2UJTine0yt8I3qZ0hk7OZV8) ![image](https://private-user-images.githubusercontent.com/23291667/286802877-f0f50a26-5a6a-41ee-ae2a-6e9381402d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNDcsIm5iZiI6MTcwMjU2Njg0NywicGF0aCI6Ii8yMzI5MTY2Ny8yODY4MDI4NzctZjBmNTBhMjYtNWE2YS00MWVlLWFlMmEtNmU5MzgxNDAyZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZmQ3YzliZGU5MzQ3ZDQ1OWRiY2FiZDQ2YzM2ZjFjYWI3N2RmNTk0YjI3MTM2MTY0N2UzNjU1N2Q3MGEwZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnJaB3gNOBuDoJxQu0-EFXVt8XRLxeHQkseQAZX01LE) ![image](https://private-user-images.githubusercontent.com/23291667/286803027-5fd5235e-a30c-4426-9853-eadfb2586d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNDcsIm5iZiI6MTcwMjU2Njg0NywicGF0aCI6Ii8yMzI5MTY2Ny8yODY4MDMwMjctNWZkNTIzNWUtYTMwYy00NDI2LTk4NTMtZWFkZmIyNTg2ZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlN2E5NzM5YmU4ZWIzMTNkOTdlOTkxZDAzMDk5NmE3MzYzODEzODUzNjA0MzExM2Y3YjNhZmE4NDZhOGVkZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W-xPAMkdu0mxhGJiamMUpvBAyghZcNPM6803r_xoau8) https://plugins.jetbrains.com/plugin/18264-beanmappingkey
> > 您好，这是我这边的详细截图
> > _Originally posted by @icellus in [#6 (comment)](https://github.com/rookie-ricardo/BeanMappingKey/issues/6#issuecomment-1833031934)_
> 
> 你已经安装的话，就是代表已经支持你这个版本了，但是我看你的截图似乎你是想说明 这个插件没办法用？如果是这样的话，我建议你
> 
> 1. 重新打开IDE，等待索引走完之后再使用，这个插件和所有插件一样依赖的是IDE内部的上下文对象，有时候它会失效。
> 2. 双击类名，右键看一下。
> 
> 版本是兼容到了2023.3的，可以给你看一下截图： <img alt="image" width="806" src="https://private-user-images.githubusercontent.com/33930171/290565191-1c3cfa79-8fe0-495d-aa5f-5355ae1a71f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjgzMzMsIm5iZiI6MTcwMjU2ODAzMywicGF0aCI6Ii8zMzkzMDE3MS8yOTA1NjUxOTEtMWMzY2ZhNzktOGZlMC00OTVkLWFhNWYtNTM1NWFlMWE3MWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MzM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MGY0OGRjODdiMDhkMzA3NGZhZmM3NWYzOGNjMWM5Zjg1OTMwMjEwNzJjNTE4OWUyY2VlOTRkZjdkZjU3NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-D_gxA6pDgsEed_O6K7tZW6ujPXzbJ76ZPlWyqZsCLc">

...原来是需要双击选中...........
我一直以为光标定位就可以ctrl+m触发的。
感谢
