### ISSUE TITLE
建议生成代码在第一行 对入参对象加个非null判断, 不然可能会有空指针的问题

### ISSUE THREAD

**Issue by 834116404** [rookie-ricardo/BeanMappingKey#8]
建议生成代码之前加个非null判断, 不然可能会有空指针的问题

**Comment by rookie-ricardo** [comment]
> 建议生成代码之前加个非null判断, 不然可能会有空指针的问题

如果为null右键的时候就不会显示可点击的按钮，从一开始就屏蔽了这个问题
